use db;
select * from customer_shopping;
select count(*) from customer_shopping;

-- what is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue from customer_shopping group by gender;

# 2. which customer use a discount but still spent more that the average purchase amount?
select customer_id , purchase_amount from customer_shopping
where discount_applied ="Yes" and purchase_amount >= (select avg(purchase_amount) from customer_shopping);

# 3. which are the top 5 products with highest average review rating?
select item_purchased , avg(review_rating) as "average_review_rating"
from customer_shopping 
group by item_purchased
order by avg(review_rating) desc
limit 5;

# 4. compare the avg purchase amount between standard andd express shipping?
select shipping_type, 
avg(purchase_amount)
from customer_shopping
where shipping_type in ('Standard','Express')
group by shipping_type;

# 5. do subscribe customers spend more? 
#compare average spend and total revenue between subscribers and non-subcribers?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping
group by subscription_status
order by total_revenue, avg_spend desc;

# 6. which 5 products have highest % of purchase with discount applied?
select item_purchased,
round(sum(case when discount_applied ="Yes" then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate desc
limit 5;

# 7. segment customer into new, returing,and loyal based on their total number of previous purchase, and show the count of each segment?
with customer_type as (
select customer_id , previous_purchases,
case
   when previous_purchases = 1 then "New"
   when previous_purchases between 2 and 10 then "Returning"
   else "Loyal"
   end as customer_segment
   from customer_shopping
   )
   
   select customer_segment, count(*) as "Number of customers"
   from customer_type
   group by customer_segment;

# 8. what are the tp 3 most purchased products within each category?

with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category ,  item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

# 9. are customers who are repeat buyers( more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status;


#10. what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping
group by age_group
order by total_revenue desc;